### ISSUE TITLE
How do you use the example NSI template with a fresh build?

### ISSUE THREAD

**Issue by avoidwork** [loopline-systems/electron-builder#111]
Hi,

Forgive my ignorance on this subject, as I rarely work with makensis; how do you use the supplied template? When I run it, I get the following:

```console
Packaging app for platform win32 x64 using electron v0.36.2
Wrote new app to dist/win/Adobe Hub-win32-x64
- Running electron-builder 2.5.0
- Starting creation of installer for ´win
undefined:13
((__t = ( publisher )) == null ? '' : __t) +
          ^
ReferenceError: publisher is not defined
    at eval (eval at <anonymous> (/Users/jamullig/Projects/nc-client/node_modules/electron-builder/node_modules/lodash.template/index.js:349:56), <anonymous>:13:11)
    at module.exports (/Users/jamullig/Projects/nc-client/node_modules/electron-builder/lib/helper/writeConfigFile.js:38:4)
    at Object.WinBuilder.build (/Users/jamullig/Projects/nc-client/node_modules/electron-builder/lib/win.js:32:26)
    at Object.Builder.build (/Users/jamullig/Projects/nc-client/node_modules/electron-builder/index.js:74:42)
    at Object.<anonymous> (/Users/jamullig/Projects/nc-client/node_modules/electron-builder/cli.js:36:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

```

Which is understandable because I'm not passing the publisher as defined on line 3: ```!define APP_PUBLISHER "<%= publisher %>"```; what's the correct way to pass that?

**Comment by stefanjudis** [comment]
@avoidwork 

Is `publisher` set in your config file?

**Comment by avoidwork** [comment]
Yes, this is the config

```
{
  "osx": {
    "title": "Adobe Hub",
    "icon": "icons/adobehub.icns",
    "background": "install-img.png",
    "icon-size": 100,
    "contents": [
      { "x": 320, "y": 115, "type": "link", "path": "/Applications" },
      { "x": 130, "y": 115, "type": "file" }
    ]
  },
  "win" : {
    "title" : "Adobe Hub",
    "version" : "2.28.999.1",
    "icon": "assets/icons/adobehub.ico",
    "nsiTemplate" : "assets/config.nsi",
    "publisher": "Adobe Systems Inc"
  }
}
```

**Comment by stefanjudis** [comment]
Can you provide the needed information as pointed out here:

https://github.com/loopline-systems/electron-builder/blob/master/CONTRIBUTING.md

and I'll have a look over the weekend.

**Comment by avoidwork** [comment]
Sure, thanks!

#### package.json
```
{
  "name": "adobe-hub",
  "version": "2.28.999",
  "release": "2.2",
  "description": "Approvals, alerts, notifcations and more",
  "private": true,
  "repository": {
    "type": "git",
    "url": "git@git.corp.adobe.com:NC/notification-center.git"
  },
  "dependencies": {},
  "devDependencies": {
    "bower": "^1.3.9",
    "electron-builder": "^2.5.0",
    "electron-packager": "^5.1.1",
    "electron-prebuilt": "^0.36.2",
    "electron-rebuild": "^1.0.2",
    "fs-extra": "^0.22.1",
    "gulp": "^3.9.x",
    "gulp-concat": "^2.5.2",
    "gulp-html2js": "^0.1.0",
    "gulp-inject": "^1.0.2",
    "gulp-jshint": "^1.9.2",
    "gulp-jshint-instafail": "^1.0.0",
    "gulp-load-plugins": "^0.8.0",
    "gulp-minify-css": "^0.3.7",
    "gulp-minify-html": "^0.1.4",
    "gulp-ng-html2js": "^0.1.8",
    "gulp-rimraf": "0.1.0",
    "gulp-sequence": "^0.3.2",
    "gulp-uglify": "0.1.0",
    "jshint-stylish": "^1.0.1",
    "semver": "^4.2.0",
    "tiny-defer": "^1.0.4",
    "yargs": "^1.3.3"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "electron ./build/index.js",
    "postinstall": "bower install",

    "clean": "rm -rf ./dist",
    "clean:osx": "rm -rf ./dist/osx",
    "clean:win": "rm -rf ./dist/win",

    "pack": "npm run clean && npm run build:osx && npm run build:win",
    "pack:osx": "npm run clean:osx && electron-packager ./build \"Adobe Hub\" --out=dist/osx --platform=darwin --arch=x64 --version=0.36.2 --icon=assets/icons/adobehub.icns",
    "pack:win": "npm run clean:win && electron-packager ./build \"Adobe Hub\" --out=dist/win --platform=win32 --arch=x64 --version=0.36.2 --icon=assets/icons/adobehub.ico",

    "build": "npm run build:osx && npm run build:win",
    "build:osx": "npm run pack:osx && electron-builder \"dist/osx/Adobe Hub-darwin-x64/Adobe Hub.app\" --platform=osx --out=\"dist/osx\" --config=assets/config.json",
    "build:win": "npm run pack:win && electron-builder \"dist/win/Adobe Hub-win32-x64\" --platform=win --out=\"dist/win\" --config=assets/config.json"
  },
  "engines": {
    "node": "4.2.x"
  },
  "contributors": [
    "cfraser@adobe.com",
    "dekrishn@adobe.com",
    "kaliamur@adobe.com",
    "jamullig@adobe.com"
  ],
  "miniapps": {
    "admin": "git@git.corp.adobe.com:NC/nc-app-administration.git",
    "qos": "git@git.corp.adobe.com:NC/nc-app-qos.git#HUB-4194",
    "pwr": "git@git.corp.adobe.com:NC/nc-app-password-reset.git#HUB-4194",
    "password-gen": "git@git.corp.adobe.com:NC/nc-app-password-gen.git#HUB-4194",
    "far": "git@git.corp.adobe.com:NC/nc-app-far.git#HUB-4194",
    "yourapphere": "git@git.corp.adobe.com:NC/nc-app-yourapphere.git#HUB-4194",
    "directory": "git@git.corp.adobe.com:NC/nc-app-directory.git#HUB-4149",
    "techcafe": "git@git.corp.adobe.com:NC/nc-app-techcafe.git#HUB-4194",
    "notification": "git@git.corp.adobe.com:NC/nc-app-notificationcenter.git"
  }
}
```

#### config.json
```
{
  "osx": {
    "title": "Adobe Hub",
    "icon": "icons/adobehub.icns",
    "background": "install-img.png",
    "icon-size": 100,
    "contents": [
      { "x": 320, "y": 115, "type": "link", "path": "/Applications" },
      { "x": 130, "y": 115, "type": "file" }
    ]
  },
  "win" : {
    "title" : "Adobe Hub",
    "version" : "2.28.999.1",
    "icon": "assets/icons/adobehub.ico",
    "nsiTemplate" : "assets/config.nsi",
    "publisher": "Adobe Systems Inc"
  }
}
```

#### terminal output
```
jamullig at kuma in ~/Projects/nc-client on HUB-4194 [!$]
$ npm run build:win

> adobe-hub@2.28.999 build:win /Users/jamullig/Projects/nc-client
> npm run pack:win && electron-builder "dist/win/Adobe Hub-win32-x64" --platform=win --out="dist/win" --config=assets/config.json


> adobe-hub@2.28.999 pack:win /Users/jamullig/Projects/nc-client
> npm run clean:win && electron-packager ./build "Adobe Hub" --out=dist/win --platform=win32 --arch=x64 --version=0.36.2 --icon=assets/icons/adobehub.ico


> adobe-hub@2.28.999 clean:win /Users/jamullig/Projects/nc-client
> rm -rf ./dist/win

Packaging app for platform win32 x64 using electron v0.36.2
Wrote new app to dist/win/Adobe Hub-win32-x64
- Running electron-builder 2.5.0
- Starting creation of installer for ´win
undefined:13
((__t = ( publisher )) == null ? '' : __t) +
          ^
ReferenceError: publisher is not defined
    at eval (eval at <anonymous> (/Users/jamullig/Projects/nc-client/node_modules/electron-builder/node_modules/lodash.template/index.js:349:56), <anonymous>:13:11)
    at module.exports (/Users/jamullig/Projects/nc-client/node_modules/electron-builder/lib/helper/writeConfigFile.js:38:4)
    at Object.WinBuilder.build (/Users/jamullig/Projects/nc-client/node_modules/electron-builder/lib/win.js:32:26)
    at Object.Builder.build (/Users/jamullig/Projects/nc-client/node_modules/electron-builder/index.js:74:42)
    at Object.<anonymous> (/Users/jamullig/Projects/nc-client/node_modules/electron-builder/cli.js:36:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build:win"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! adobe-hub@2.28.999 build:win: `npm run pack:win && electron-builder "dist/win/Adobe Hub-win32-x64" --platform=win --out="dist/win" --config=assets/config.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the adobe-hub@2.28.999 build:win script 'npm run pack:win && electron-builder "dist/win/Adobe Hub-win32-x64" --platform=win --out="dist/win" --config=assets/config.json'.
npm ERR! This is most likely a problem with the adobe-hub package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run pack:win && electron-builder "dist/win/Adobe Hub-win32-x64" --platform=win --out="dist/win" --config=assets/config.json
npm ERR! You can get their info via:
npm ERR!     npm owner ls adobe-hub
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jamullig/Projects/nc-client/npm-debug.log

jamullig at kuma in ~/Projects/nc-client on HUB-4194 [!$]
$ 
```

node: v0.12.7
npm: 2.11.3
os: OS X 10.11.2, with brew + makensis + wine

**Comment by stefanjudis** [comment]
Mmh - looks like a readme typo thing. Can you check if #110 helps you?

**Comment by avoidwork** [comment]
That's sorted out, it builds osx fine; I noticed it yesterday too ;)

**Comment by stefanjudis** [comment]
Alright. Got it...

Thing is - the publisher option was documented in master ( it wasn't on `npm` ) and not released yet.

Just released new minor version `v2.6.0` which includes the `publisher` variable used in your custom nsi script. :)

I've got an up and running build included here: https://github.com/stefanjudis/blocky/blob/master/package.json maybe this helps also in the future.

Will include it readme here, too.

I think this solves your issue and I'll close here. Feel free to open if you have still troubles.

**Comment by avoidwork** [comment]
Thanks! I'll give it a try when I have some time this weekend.

**Comment by avoidwork** [comment]
Hi,

It worked flawlessly the first try! Thanks!

**Comment by stefanjudis** [comment]
:tada: :tada: :tada:
