### ISSUE TITLE
Cannot load the config.file 

### ISSUE THREAD

**Issue by truenoda** [loopline-systems/electron-builder#114]
I am really confused about the three .json file,I tried to use the command 
electron-builder app --platform=win --out=dist/win --config=config.json 
but still throw errors,absolute path didn't work.
And I really want to know that " npm run pack " and "electron-builder"need which json file.
Both of them throw error...

>C:\Users\tracy\AppData\Roaming\npm\node_modules\electron-builder\cli.js:41
    throw error;
    ^
Error: Could not load config file
    at Object.Builder.build (C:\Users\tracy\AppData\Roaming\npm\node_modules\ele
ctron-builder\index.js:69:26)
    at Object.<anonymous> (C:\Users\tracy\AppData\Roaming\npm\node_modules\elect
ron-builder\cli.js:37:9)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by stefanjudis** [comment]
Please provide needed information.

https://github.com/loopline-systems/electron-builder/blob/master/CONTRIBUTING.md

**Comment by stefanjudis** [comment]
Closing due to inactivitity.
