### ISSUE TITLE
Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by delvedor** [loopline-systems/electron-builder#15]
Hi, I'm using this package with this npm-script
```javascript
"pack:win": "npm run build:win && electron-builder \"dist/win/MyApp-win32\" --platform=win --out=\"dist/win\" --config=pack.json"
```
and I get this error (the packaging with electron-packager goes well):

```javascript
...
Packaging app for platform win32 x64 using electron v0.28.1
Wrote new app to dist/win/MyApp-win32
- Starting build for ´win´ - 
path.js:422
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:422:13)
    at _copyAssetsToTmpFolder (/.../.../MyApp/node_modules/electron-builder/lib/win.js:112:10)
    at Object.WinBuilder.build (/.../.../MyApp/node_modules/electron-builder/lib/win.js:36:5)
    at Object.Builder.build (/.../.../MyApp/node_modules/electron-builder/index.js:59:42)
    at Object.<anonymous> (/.../.../MyApp/node_modules/electron-builder/cli.js:26:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```
What am I doing wrong?

**Comment by stefanjudis** [comment]
@delvedor 

Can you provide your `pack.json`?

**Comment by delvedor** [comment]
@stefanjudis sure, here it is:
```javascript
{
  "win" : {
    "title" : "MyApp"
  }
}
```

**Comment by stefanjudis** [comment]
Can you set an icon?

We're still meaning defaults ( #12 ). Sorry for that.

**Comment by delvedor** [comment]
By providing an icon all goes well, thanks!
Maybe can be a good idea put a default-icon if not provided in the configuration file.

**Comment by stefanjudis** [comment]
Cool. Glad to hear that. :)

Yeah, I'm planning a make over (hopefully) next week to provide defaults and make the setup flow less complicated ( #12 ).

I'm closing here, as it's solved.
Feel free to reopen if you run in any more troubles.
