### ISSUE TITLE
path.win32 doesn't exist when running on Windows for Windows

### ISSUE THREAD

**Issue by adam-lynch** [loopline-systems/electron-builder#157]
```shell
 electron-builder myApp-win32-ia32 --out=dist/installers --platform=win --config=config.json
- Running electron-builder 2.7.2
- Starting creation of installer for ´win

C:\Users\Digital\AppData\Roaming\npm\node_modules\electron-builder\cli.js:63
    throw error;
          ^
TypeError: Cannot call method 'normalize' of undefined
    at _windowsify (C:\Users\Digital\AppData\Roaming\npm\node_modules\electron-builder\lib\win.js:146:18)
    at Object.WinBuilder.build (C:\Users\Digital\AppData\Roaming\npm\node_modules\electron-builder\lib\win.js:40:25)
    at Object.Builder.build (C:\Users\Digital\AppData\Roaming\npm\node_modules\electron-builder\index.js:76:44)
    at Object.<anonymous> (C:\Users\Digital\AppData\Roaming\npm\node_modules\electron-builder\cli.js:57:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

It works if I change this in `_windowsify` in `win.js`:

```diff
- p = path.win32.normalize( p );
+ p = path.normalize( p );
```

**Comment by stefanjudis** [comment]
What node version are you on?

**Comment by adam-lynch** [comment]
@stefanjudis v0.10.20

**Comment by stefanjudis** [comment]
That's too old. `normalize` is available in newer versions... Official support is node 4+ when I remember correctly. ( am on the phone ).

**Comment by develar** [comment]
@stefanjudis To prevent such issues now we explicitly require NodeJS v4 —. https://github.com/loopline-systems/electron-builder/blob/master/package.json#L21
