### ISSUE TITLE
Building for linux fails because of missing child_process.execSync

### ISSUE THREAD

**Issue by adam-lynch** [loopline-systems/electron-builder#158]
First I tried this on Windows and it failed for that reason. The docs say you may need fpm for Mac / Linux but doesn't mention Windows, is it supported at all for creating a Linux installer?

I then tried on my Mac. I got the following

```shell
electron-builder releases/electron-quick-start-linux-ia32/ --out=releases/installers/ --platform=linux --config=config.json
- Running electron-builder 2.7.2
- Starting creation of installer for ´linux

/usr/local/lib/node_modules/electron-builder/cli.js:63
    throw error;
          ^
TypeError: Object #<Object> has no method 'execSync'
    at _buildPackage (/usr/local/lib/node_modules/electron-builder/lib/linux.js:166:16)
    at Object.LinuxBuilder.build (/usr/local/lib/node_modules/electron-builder/lib/linux.js:53:5)
    at Object.Builder.build (/usr/local/lib/node_modules/electron-builder/index.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/cli.js:57:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

Installing fpm didn't help. Installing gnutar didn't help.

**Comment by develar** [comment]
Please see https://github.com/loopline-systems/electron-builder/issues/159#issuecomment-185561841

**Comment by adam-lynch** [comment]
@develar can you confirm which platforms can build for Linux?

**Comment by develar** [comment]
@adam-lynch On OS X without any problems. Windows — please see https://github.com/jordansissel/fpm/issues/505 You can build on Windows, but as always on Windows, it is not easy — you need to install cygwin... In the near future (several weeks) it will be documented and supported, but currently I cannot give you detailed instruction.

**Comment by adam-lynch** [comment]
@develar that's good enough thanks
