### ISSUE TITLE
fails if `--out` dir does not yet exist

### ISSUE THREAD

**Issue by freewil** [loopline-systems/electron-builder#22]
The output directory should be created if it doesn't exist yet

```
Error: Error running `hdiutil`! Exit code was 1
    at ChildProcess.<anonymous> (electron-builder/node_modules/appdmg/lib/util.js:32:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
```

**Comment by stefanjudis** [comment]
@freewil 

Hmm, how did you reach this. I'm just trying it, and it's creating the directory fine.

**Comment by freewil** [comment]
`electron-builder my.app --platform=osx --out=doesnotexist --config=electron-builder.json`

**Comment by freewil** [comment]
If you still can't reproduce it, you should be able to with this command:

```
$ git clone https://github.com/freewil/bitcoin-bar.git && \
  cd bitcoin-bar && \
  npm install && \
  rm -r release && \
  npm run release
```

**Comment by justinmchase** [comment]
Try using `--out=./doesnotexist`
