### ISSUE TITLE
Github publishing not working on Linux

### ISSUE THREAD

**Issue by russss** [loopline-systems/electron-builder#229]
When building on Linux, the GitHub publisher can't find the .deb files for some reason:

```
Unhandled rejection Error: ENOENT: no such file or directory, stat 'IRCCloud-0.1.2-i386.deb'
    at Error (native)
From previous event:
    at GitHubPublisher.<anonymous> (/vagrant/node_modules/electron-builder/src/gitHubPublisher.ts:77:32)
    at [object Generator].next (native)
From previous event:
    at tsAwaiter (/vagrant/node_modules/electron-builder/src/awaiter.ts:10:51)
    at GitHubPublisher.upload (/vagrant/node_modules/electron-builder/src/gitHubPublisher.ts:69:28)
    at /vagrant/node_modules/electron-builder/src/builder.ts:85:73
From previous event:
    at EventEmitter.<anonymous> (/vagrant/node_modules/electron-builder/src/builder.ts:85:19)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at LinuxPackager.dispatchArtifactCreated (/vagrant/node_modules/electron-builder/src/platformPackager.ts:84:28)
    at /vagrant/node_modules/electron-builder/src/linuxPackager.ts:118:24
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at LinuxPackager.<anonymous> (/vagrant/node_modules/electron-builder/src/linuxPackager.ts:118:8)
    at [object Generator].next (native)
From previous event:
    at tsAwaiter (/vagrant/node_modules/electron-builder/src/awaiter.ts:10:51)
    at Object.build (/vagrant/node_modules/electron-builder/src/builder.ts:30:55)
    at Object.<anonymous> (/vagrant/node_modules/electron-builder/src/build-cli.ts:41:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

The file `IRCCloud-0.1.2-i386.deb` definitely exists under `dist/`, so I suspect there's something specific to the deb building workflow which isn't sending the correct path to the publisher.

**Comment by russss** [comment]
Thanks for the quick fix!
