### ISSUE TITLE
Wrong path to package when build Mac dist

### ISSUE THREAD

**Issue by EvgeneOskin** [loopline-systems/electron-builder#247]
Hello, 

I've got error bellow, when I tried to generate .dmg with `./node_modules/.bin/build --dist` command. 

```
...
Signing app
/Users/eoskin/projects/sawebshell/dist/Serverauditor-darwin-x64/Serverauditor.app: No such file or directory

Error: Command failed: codesign --deep --force --sign Mac Developer: eoskin@crystalnix.com (DTNNV67VE5) /Users/eoskin/projects/sawebshell/dist/Serverauditor-darwin-x64/Serverauditor.app --keychain csc-6512e94cb294009e.keychain
/Users/eoskin/projects/sawebshell/dist/Serverauditor-darwin-x64/Serverauditor.app: No such file or directory

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
From previous event:
    at Object.exec (/Users/eoskin/projects/sawebshell/node_modules/electron-builder/src/util.ts:68:10)
    at Object.sign (/Users/eoskin/projects/sawebshell/node_modules/electron-builder/src/codeSign.ts:78:14)
    at MacPackager.signMac (/Users/eoskin/projects/sawebshell/node_modules/electron-builder/src/macPackager.ts:51:18)
    at MacPackager.<anonymous> (/Users/eoskin/projects/sawebshell/node_modules/electron-builder/src/macPackager.ts:37:23)
From previous event:
    at tsAwaiter (/Users/eoskin/projects/sawebshell/node_modules/electron-builder/src/awaiter.ts:10:51)
    at Object.build (/Users/eoskin/projects/sawebshell/node_modules/electron-builder/src/builder.ts:30:55)
    at Object.<anonymous> (/Users/eoskin/projects/sawebshell/node_modules/electron-builder/src/build-cli.ts:41:2)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3
```

Build config is 
```
{
...
  "build": {
    "appname": "Serverauditor",
    "app-bundle-id": "Serverauditor",
    "app-category-type": "public.app-category.utilities",
    "iconUrl": "",
    "asar": true,
    "dir": ".",
    "out": "dist/desktop"
  }
...
}
```

Actual path to .app file is `/Users/eoskin/projects/sawebshell/dist/desktop/Serverauditor-darwin-x64/Serverauditor.app`.

Did I something wrong? Do you need extra info?

**Comment by develar** [comment]
Please don't specify `"dir": ".",` and `"out": "dist/desktop"` — must be removed.

` "asar": true,` is not required — asar by default.

**Comment by EvgeneOskin** [comment]
Thanks!

**Comment by develar** [comment]
BTW, we remove such incorrect options in the upcoming release.
