### ISSUE TITLE
"Error: Building for ´osx´ is not supported" when I run "npm run pack:osx"

### ISSUE THREAD

**Issue by jurgob** [loopline-systems/electron-builder#25]
Hi, 
when I try to run npm run pack:osx i get the following error error:

```bash
MLGBXXXXXX-2:ElectronTest jurgo.boemo$ npm run pack:osx

> ElectronTest@1.0.0 pack:osx /Users/jurgo.boemo/Workspace/ElectronTest
> npm run build:osx && electron-builder "dist/osx/Loopline Systems.app" --platform=osx --out="dist/osx" --config=packager.json


> ElectronTest@1.0.0 build:osx /Users/jurgo.boemo/Workspace/ElectronTest
> npm run clean:osx && electron-packager ./app "Loopline Systems" --out=dist/osx --platform=darwin --arch=x64 --version=0.25.3 --icon=assets/osx/loopline.icns


> ElectronTest@1.0.0 clean:osx /Users/jurgo.boemo/Workspace/ElectronTest
> rm -rf ./dist/osx

Packaging app for platform darwin x64 using electron v0.25.3
Wrote new app to dist/osx/Loopline Systems.app
/Users/jurgo.boemo/Workspace/ElectronTest/node_modules/electron-builder/cli.js:30
    throw error;
          ^
Error: Building for ´osx´ is not supported
    at Object.Builder.build (/Users/jurgo.boemo/Workspace/ElectronTest/node_modules/electron-builder/index.js:55:9)
    at Object.<anonymous> (/Users/jurgo.boemo/Workspace/ElectronTest/node_modules/electron-builder/cli.js:26:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "pack:osx"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! ElectronTest@1.0.0 pack:osx: `npm run build:osx && electron-builder "dist/osx/Loopline Systems.app" --platform=osx --out="dist/osx" --config=packager.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ElectronTest@1.0.0 pack:osx script 'npm run build:osx && electron-builder "dist/osx/Loopline Systems.app" --platform=osx --out="dist/osx" --config=packager.json'.
npm ERR! This is most likely a problem with the ElectronTest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:osx && electron-builder "dist/osx/Loopline Systems.app" --platform=osx --out="dist/osx" --config=packager.json
npm ERR! You can get their info via:
npm ERR!     npm owner ls ElectronTest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jurgo.boemo/Workspace/ElectronTest/npm-debug.log
```

you can find my code here: https://github.com/jurgob/electron-builder-seed

**Comment by stefanjudis** [comment]
Hey,

you're using the wrong version of electron-builder.

```
  // your package.json
  "dependencies": {
    "electron-packager": "^4.0.2",
    "electron-prebuilt": "^0.25.2",
    "electron-builder": "^1.0.0"
  }

  // how it should be
  "dependencies": {
    "electron-packager": "^4.0.2",
    "electron-prebuilt": "^0.25.2",
    "electron-builder": "^2.0.0"
  }
```

I just cloned your repo and with version `v2.0.0` it's working fine.

```
➜  electron-builder-seed git:(master) ✗ npm run pack:osx
Packaging app for platform darwin x64 using electron v0.25.3
Wrote new app to dist/osx/Loopline Systems.app
- Starting build for ´osx´ -
Writing temporary ´appdmg.json´
Wrote temporary ´appdmg.json´
Kicking off ´appdmg´
appdmg: [1] Looking for target
appdmg: [2] Reading JSON Specification
appdmg: [3] Parsing JSON Specification
appdmg: [4] Validating JSON Specification
appdmg: [5] Looking for files
appdmg: [6] Calculating size of image
appdmg: [7] Creating temporary image
appdmg: [8] Mounting temporary image
appdmg: [9] Making hidden background folder
appdmg: [10] Copying background
appdmg: [11] Reading background dimensions
appdmg: [12] Copying icon
appdmg: [13] Setting icon
appdmg: [14] Creating links
appdmg: [15] Copying files
appdmg: [16] Making all the visuals
appdmg: [17] Blessing image
appdmg: [18] Unmounting temporary image
appdmg: [19] Finalizing image
appdmg: [20] Removing temporary image
Finished ´appdmg´
- Created installer for osx -
```

**Comment by jurgob** [comment]
It works, thanks!
