### ISSUE TITLE
Error on running electron builder

### ISSUE THREAD

**Issue by hhammoud01** [loopline-systems/electron-builder#31]
This is the output after doing electron-builder myApp.app --platform =osx --output=./output --overwrite --config=./assets/config.json

Please help :/

- Starting build for ´osx´ - 
Writing temporary ´appdmg.json´
Wrote temporary ´appdmg.json´
Kicking off ´appdmg´
module.js:338
    throw err;
          ^
Error: Cannot find module 'appdmg'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.OSXBuilder.build (/usr/local/lib/node_modules/electron-builder/lib/osx.js:52:18)
    at Object.Builder.build (/usr/local/lib/node_modules/electron-builder/index.js:59:42)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/cli.js:26:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

**Comment by hhammoud01** [comment]
Solved this issue by reinstalling node and electron-builder's required packages
