### ISSUE TITLE
TypeError: Cannot call method 'normalize' of undefined

### ISSUE THREAD

**Issue by bitomule** [loopline-systems/electron-builder#33]
I get this error trying to build windows.

This is the full log:

```
electron-builder dist/win/myapp --platform=win --out=./installers/win --config=config.json
- Starting build for ´win´ -

/usr/local/lib/node_modules/electron-builder/lib/win.js:127
  p = path.win32.normalize( p );
                 ^
TypeError: Cannot call method 'normalize' of undefined
    at _windowsify (/usr/local/lib/node_modules/electron-builder/lib/win.js:127:18)
    at Object.WinBuilder.build (/usr/local/lib/node_modules/electron-builder/lib/win.js:31:17)
    at Object.Builder.build (/usr/local/lib/node_modules/electron-builder/index.js:59:42)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/cli.js:26:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by Akamaozu** [comment]
@bitomule did you solve this problem? if so .. mind sharing how?

**Comment by davidcrawford** [comment]
I saw the same issue since apt-get on ubuntu had installed v0.13.0-pre, which doesn't include the v0.12 change `path` to include `win32`.  Installed v0.12.7 and the problem went away.

**Comment by bitomule** [comment]
If you are on osx/linux check you have installed:

````
brew install wine makensis
````

And that you're running node 0.10.33 for osx and linux builds and 0.12.0 for windows. That fixed all our issues. In our package.json we've configured scripts that change node version, build and package for all the platforms (32 and 64 bits)

**Comment by stefanjudis** [comment]
We'll tackle this for the future. :bowtie: 

#43

**Comment by Akamaozu** [comment]
@bitomule thanks for the details. that solved the problem :)

**Comment by bitomule** [comment]
Great @Akamaozu :)
