### ISSUE TITLE
Building win32 on Mac

### ISSUE THREAD

**Issue by xwartz** [loopline-systems/electron-builder#93]
Hi,
When I try to run pack:win, i get the following error:

```bash
makensis: Error while loading icon from "icon.ico": invalid icon file
Error in macro MUI_INTERFACE on macroline 64
Error in macro MUI_PAGE_INIT on macroline 3

makensis: Error in macro MUI_PAGE_WELCOME on macroline 5
Error in script "/var/folders/gl/lfyn6py57qxdj6695y2sfyjm0000gn/T/49geudg9a5k48gosss0ko.tpl" on line 24 -- aborting creation process

Finished makensis with code 1
/Users/xwartz/work/project/web/task/src/main/webapp/static/node_modules/electron-builder/cli.js:40
    throw error;
    ^

Error: makensis failed
    at ChildProcess.<anonymous> (/Users/xwartz/work/project/web/task/src/main/webapp/static/node_modules/electron-builder/lib/win.js:84:26)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

npm scripts:
```js
"build:win": "electron-packager ./ DiDaWin --out=dist/win --platform=win32 --arch=ia32 --version=0.36.0 --icon=img/icon_128.png --overwrite",
"pack:win": "npm run build:win && electron-builder \"dist/osx/DiDaWin-win32-ia32/DiDaWin.app\" --platform=win32 --out=\"dist/win\" --config=packager.json"
```

packager.json
```js
{
    "win" : {
        "title": "DiDa",
        "icon": "img/icon_128.png"
    }
}
```

What can I do to fix this ?

**Comment by stefanjudis** [comment]
Can you try an `.ico` file AS icon? I don't think PNG ist supported.

**Comment by xwartz** [comment]
I tried but throwed the same error:

```shell
File: Returning to: "/Users/xwartz/work/project/web/task/src/main/webapp/static/dist/osx/DiDaWin-win32-ia32/DiDaWin.app"
File: "\Users\xwartz\work\project\web\task\src\main\webapp\static\dist\osx\DiDaWin-win32-ia32\DiDaWin.app\*" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "/var/folders/gl/lfyn6py57qxdj6695y2sfyjm0000gn/T/1yxim29qol28owcwsgwog.tpl" on line 59 -- aborting creation process

Finished makensis with code 1
/Users/xwartz/work/project/web/task/src/main/webapp/static/node_modules/electron-builder/cli.js:40
    throw error;
    ^

Error: makensis failed
    at ChildProcess.<anonymous> (/Users/xwartz/work/project/web/task/src/main/webapp/static/node_modules/electron-builder/lib/win.js:84:26)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

```

**Comment by stefanjudis** [comment]
Any chance to provide me your icon and config? So that I can try it myself tonight. :)

**Comment by xwartz** [comment]
I made a mistake. I copied an incorrect directory.

Thanks.
