### ISSUE TITLE
Invalid platform

### ISSUE THREAD

**Issue by tborychowski** [loopline-systems/electron-builder#97]
I'm trying to build osx app on ubuntu and I'm getting an error:
```sh
electron-builder \"dist/osx/MyApp.app\" --platform=osx --out=\"dist/osx\" --config=packager.json
- Running electron-builder 2.4.0
/usr/local/lib/node_modules/electron-builder/cli.js:40
    throw error;
    ^

Error: Invalid platform.
    at Object.OSXBuilder.build (/usr/local/lib/node_modules/electron-builder/lib/osx.js:28:24)
    at Object.Builder.build (/usr/local/lib/node_modules/electron-builder/index.js:74:42)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/cli.js:36:9)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
```
My `packager.json` is exactly the same as in your readme example.

**Comment by havenchyk** [comment]
The error message isn't very helpful, but it's from `node-appdmg` and it mean that there is no way to build `dmg` on non-osx.

**Comment by havenchyk** [comment]
Look at https://github.com/LinusU/node-appdmg/issues/14 for details.

**Comment by stefanjudis** [comment]
I think I'll close this one for now as there is no way to fix it here. :(

Feel free to reopen later on. :)

**Comment by havenchyk** [comment]
@stefanjudis is there this info in the readme?
